apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tv2oya03o-go 
  janus-idp.io/tekton: tv2oya03o-go
  backstage.io/kubernetes-id: tv2oya03o-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tv2oya03o-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml