apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tv2oya03o-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tv2oya03o-go 
  name: tv2oya03o-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tv2oya03o-go 
